var = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(var))
print('só tem espaços? ', var.isspace())
print('é um número? ', var.isnumeric())
print('é alfabético? ', var.isalpha())
print('é alfanumérico? ', var.isalnum())
print('é tudo maiúsculo? ', var.isupper())
print('é tudo minúsculo? ', var.islower())
print('está capitalizada? ', var.istitle())